/**
 * The Architeksoft WebViewer: the customer-facing 3D kitchen configurator, a fully static app served
 * from public/webviewer/ (copied there by `npm run webviewer:sync`, see scripts/sync-webviewer.mjs).
 * The site embeds its customer.html in an iframe on the same origin, so the viewer can also follow
 * `<html lang>` of the page.
 *
 * Safe to import from client components (no Node APIs).
 */
import { WEBVIEWER_SYNCED_BUNDLES } from "./webviewer-build";

/** Must keep its trailing slash: the page loads app/ and vendor/ by relative URLs. */
export const VIEWER_BASE = "/webviewer/";

/**
 * Kitchens the site may open: the bundle folders published in public/webviewer/, as listed in
 * webviewer.config.json (demo mode: curated decors only). Generated by `npm run webviewer:sync`.
 */
export const KITCHEN_BUNDLES = WEBVIEWER_SYNCED_BUNDLES;
export type KitchenBundle = (typeof KITCHEN_BUNDLES)[number];
/** The first kitchen in webviewer.config.json. */
export const DEFAULT_BUNDLE: KitchenBundle = KITCHEN_BUNDLES[0];

export type ViewerLang = "hy" | "ru" | "en";
const VIEWER_LANG: Record<string, ViewerLang> = { hy: "hy", am: "hy", ru: "ru", en: "en" };

/** Site locale (hy, ru, en, ru-RU, am…) → viewer language; Armenian when unknown. */
export function viewerLang(siteLocale: string | null | undefined): ViewerLang {
  return VIEWER_LANG[String(siteLocale ?? "").slice(0, 2).toLowerCase()] ?? "hy";
}

export function isKitchenBundle(v: unknown): v is KitchenBundle {
  return typeof v === "string" && (KITCHEN_BUNDLES as readonly string[]).includes(v);
}

/**
 * A `cfg` value as the viewer's own share links write it (`fronts:white,carcass:p:EGGER_W1000_ST9`).
 * Only forwarded, never built here; anything outside that alphabet is dropped.
 */
function safeCfg(v: string | null | undefined): string | null {
  return v && v.length <= 2000 && /^[A-Za-z0-9_.:,\-]+$/.test(v) ? v : null;
}

export type ViewerParams = {
  bundle?: string | null;
  lang: ViewerLang;
  cfg?: string | null;
  doors?: boolean;
  tour?: boolean;
  /**
   * The public showcase (`mode=demo`): the viewer adds its demo behaviour — colour showreel until the first
   * interaction, the "Demo preview" card with "Start your project". Omit it for a client's own project: the
   * viewer's default is the full, unrestricted client mode.
   */
  demo?: boolean;
  /** `ui=compact`: layout for a small box (homepage) — panel folded, one-row colour strip over the stage. */
  compact?: boolean;
};

/** `{VIEWER_BASE}customer.html?bundle=…&lang=…` — a bundle outside the allowlist becomes the default. */
export function viewerSrc({ bundle, lang, cfg, doors, tour, demo, compact }: ViewerParams): string {
  const q = new URLSearchParams();
  q.set("bundle", isKitchenBundle(bundle) ? bundle : DEFAULT_BUNDLE);
  q.set("lang", lang);
  if (demo) q.set("mode", "demo");
  if (compact) q.set("ui", "compact");
  const c = safeCfg(cfg);
  if (c) q.set("cfg", c);
  if (doors) q.set("doors", "1");
  if (tour === false) q.set("tour", "0");
  return `${VIEWER_BASE}customer.html?${q.toString()}`;
}

/** Host-page query (`?bundle=&cfg=&doors=1`) → the viewer options it may forward. */
export function viewerParamsFromQuery(sp: Record<string, string | string[] | undefined>): Pick<ViewerParams, "bundle" | "cfg" | "doors"> {
  const one = (k: string) => {
    const v = sp[k];
    return Array.isArray(v) ? v[0] : v;
  };
  const bundle = one("bundle");
  return { bundle: isKitchenBundle(bundle) ? bundle : DEFAULT_BUNDLE, cfg: safeCfg(one("cfg")), doors: one("doors") === "1" };
}
