// Generated by scripts/sync-webviewer.mjs from webviewer.config.json — do not edit by hand.
/** ClaudeKitchen commit the files in public/webviewer/ were copied from. */
export const WEBVIEWER_COMMIT = "604366d";
/** CSP source for the one inline script of customer.html (its importmap). */
export const WEBVIEWER_IMPORTMAP_HASH = "'sha256-EF5DAX1B7V5EDA4L+W7eWsebv7OqQAydNWvxqc4ahOQ='";
/** Bundles published in public/webviewer/; the first one is the site's default kitchen. */
export const WEBVIEWER_SYNCED_BUNDLES = ["bundle_showcase"] as const;
